-- AI-generated questions pool — shared across all users
-- Questions generated by AI are stored here and reused (source='pool') or fresh (source='generated')
-- Run: wrangler d1 execute CORTEX_DB --file=migrations/0007_ai_generated_questions.sql

CREATE TABLE IF NOT EXISTS ai_generated_questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  locale TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('logic','math','vocab','event')),
  question TEXT NOT NULL,
  options TEXT NOT NULL,       -- JSON array of 4 option strings
  answer INTEGER NOT NULL,     -- 0-based correct option index
  explanation TEXT NOT NULL,
  difficulty REAL NOT NULL DEFAULT 0,
  discrimination REAL NOT NULL DEFAULT 1.0,
  guessing REAL NOT NULL DEFAULT 0.25,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  neuron_cost REAL NOT NULL DEFAULT 0,
  created_for_license TEXT,    -- license key of the user who first generated it
  created_at TEXT DEFAULT (datetime('now')),
  times_used INTEGER DEFAULT 1,
  last_used_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_q_locale_type ON ai_generated_questions(locale, type);
CREATE INDEX IF NOT EXISTS idx_ai_q_difficulty ON ai_generated_questions(difficulty);
